# Generated by Django 3.1.14 on 2024-06-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_storage', models.DateTimeField(verbose_name='начало хранения')),
                ('end_storage', models.DateTimeField(verbose_name='конец хранения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='botapp.client', verbose_name='клиент')),
            ],
        ),
    ]
